version: '3.8'

services:
  node-server:
    build: ./backend
    ports:
      - "8000:8000"
    # Add any other configurations as needed

  react-app:
    build: ./frontend
    ports:
      - "3000:3000"
    # Add any other configurations as needed
